version: 1.0.{build}
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
  - nuget restore
build:
  project: Multiformats.Address.sln
  publish_nuget: true
  include_nuget_references: true
  parallel: true
  verbosity: minimal
deploy:
  provider: NuGet
  api_key:
    secure: WcDqU36pLPvA+s5D4N0VEsi7AZGewvf4croE/D3rh3F+iqiztq9w5gHbrhgoTNS9
  on:
    branch: master
after_test:
  - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:".\packages\NUnit.ConsoleRunner.3.6.0\tools\nunit3-console.exe" -targetargs:".\Multiformats.Address.Tests\bin\Release\Multiformats.Address.Tests.dll" -filter:"+[Multiformats.Address]* -[Multiformats.Address.Benchmarks]* -[Multiformats.Address.Tests]*" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All -output:.\coverage.xml
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - pip install codecov
  - codecov -f ".\coverage.xml"